// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response when accepting an invite.
 */
export type AcceptInviteResponse = {
  success: boolean
  quiz_id: string
  quiz_title: string
  message: string
}

/**
 * A single page/item within a module with coverage annotations.
 */
export type AnnotatedPage = {
  /**
   * Page or document title
   */
  title: string
  /**
   * Annotated sentences with coverage data
   */
  sentences: Array<SentenceCoverage>
  /**
   * Total word count of the page
   */
  word_count: number
  /**
   * Count of sentences by coverage level
   */
  coverage_summary: {
    [key: string]: number
  }
}

export type Body_quiz_upload_manual_module = {
  /**
   * Module name
   */
  name: string
  /**
   * Direct text content
   */
  text_content?: string | null
  /**
   * Single PDF file upload (legacy)
   */
  file?: (Blob | File) | null
  /**
   * Multiple PDF files upload
   */
  files?: Array<Blob | File>
}

/**
 * Schema for bulk approving multiple questions.
 */
export type BulkApproveRequest = {
  /**
   * List of question IDs to approve
   */
  question_ids: Array<string>
}

/**
 * Schema for bulk deleting/rejecting multiple questions.
 */
export type BulkDeleteRequest = {
  /**
   * List of question IDs to delete
   */
  question_ids: Array<string>
  /**
   * Reason for rejection (applies to all questions)
   */
  rejection_reason?: RejectionReason | null
  /**
   * Additional feedback for rejection
   */
  rejection_feedback?: string | null
}

/**
 * Response schema for bulk operations.
 */
export type BulkOperationResponse = {
  /**
   * Number of questions successfully processed
   */
  success_count: number
  /**
   * Number of questions that failed to process
   */
  failed_count: number
  /**
   * IDs of questions that failed
   */
  failed_ids?: Array<string>
  /**
   * Summary message of the operation
   */
  message: string
}

/**
 * Canvas course information.
 */
export type CanvasCourse = {
  id: number
  name: string
}

/**
 * Canvas module (chapter/section) information.
 */
export type CanvasModule = {
  id: number
  name: string
}

/**
 * Response schema for a collaborator.
 */
export type CollaboratorResponse = {
  id: string
  user_id: string
  user_name: string | null
  added_at: string | null
}

/**
 * Overall coverage statistics for a module.
 */
export type CoverageStatistics = {
  /**
   * Total sentences in content
   */
  total_sentences: number
  /**
   * Sentences with coverage >= threshold
   */
  covered_sentences: number
  /**
   * Percentage of sentences covered
   */
  coverage_percentage: number
  /**
   * Total questions analyzed
   */
  total_questions: number
  /**
   * Longest consecutive uncovered stretch
   */
  largest_gap_sentences: number
}

/**
 * Specific failure reasons for detailed error tracking.
 */
export type FailureReason =
  | "content_extraction_error"
  | "no_content_found"
  | "llm_generation_error"
  | "no_questions_generated"
  | "canvas_export_error"
  | "network_error"
  | "validation_error"

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Public invite info (without accepting).
 */
export type InviteInfoResponse = {
  quiz_title: string
  owner_name: string | null
  is_valid: boolean
  message?: string | null
}

/**
 * Response schema for manual module creation.
 */
export type ManualModuleResponse = {
  /**
   * Generated manual module ID
   */
  module_id: string
  /**
   * Module name
   */
  name: string
  /**
   * Preview of processed content
   */
  content_preview: string
  /**
   * Full processed content
   */
  full_content: string
  /**
   * Word count of processed content
   */
  word_count: number
  /**
   * Processing details
   */
  processing_metadata?: {
    [key: string]: unknown
  }
}

/**
 * Coverage data for an entire module.
 */
export type ModuleCoverage = {
  /**
   * Module identifier
   */
  module_id: string
  /**
   * Human-readable module name
   */
  module_name: string
  /**
   * Annotated pages in the module
   */
  pages: Array<AnnotatedPage>
  /**
   * Percentage of sentences with coverage above threshold
   */
  overall_coverage_percentage: number
  /**
   * Total number of sentences analyzed
   */
  total_sentences: number
  /**
   * Number of sentences with coverage above threshold
   */
  covered_sentences: number
  /**
   * Number of consecutive uncovered sentence groups
   */
  gap_count: number
}

/**
 * Response for single module coverage analysis.
 */
export type ModuleCoverageResponse = {
  /**
   * Quiz UUID
   */
  quiz_id: string
  /**
   * Coverage data for the module
   */
  module: ModuleCoverage
  /**
   * Question-to-content mappings
   */
  question_mappings: Array<QuestionMapping>
  /**
   * Summary statistics
   */
  statistics: CoverageStatistics
  /**
   * ISO timestamp when coverage was computed
   */
  computed_at: string
}

/**
 * Summary of a module available for coverage analysis.
 */
export type ModuleListItem = {
  /**
   * Module identifier
   */
  module_id: string
  /**
   * Human-readable module name
   */
  module_name: string
  /**
   * Number of questions generated from this module
   */
  question_count: number
  /**
   * Whether extracted content exists for this module
   */
  has_content: boolean
}

/**
 * Response listing modules available for coverage analysis.
 */
export type ModuleListResponse = {
  /**
   * Quiz UUID
   */
  quiz_id: string
  /**
   * Modules available for coverage analysis
   */
  modules: Array<ModuleListItem>
}

/**
 * Schema for module selection with multiple question type batches.
 */
export type ModuleSelection = {
  name: string
  /**
   * Question type batches (1-4 per module)
   */
  question_batches: Array<QuestionBatch>
  /**
   * Module source: 'canvas' or 'manual'
   */
  source_type?: string
  /**
   * Full content for manual modules
   */
  content?: string | null
  /**
   * Word count for manual modules
   */
  word_count?: number | null
  /**
   * Processing metadata for manual modules
   */
  processing_metadata?: {
    [key: string]: unknown
  } | null
  /**
   * Content type for manual modules (e.g., 'text', 'pdf')
   */
  content_type?: string | null
}

/**
 * Schema for a batch of questions of a specific type and difficulty.
 */
export type QuestionBatch = {
  question_type: QuestionType
  /**
   * Number of questions (1-20)
   */
  count: number
  difficulty: QuestionDifficulty
}

/**
 * Schema for creating a new question.
 */
export type QuestionCreateRequest = {
  quiz_id: string
  question_type: QuestionType
  /**
   * Question type-specific data
   */
  question_data: {
    [key: string]: unknown
  }
  difficulty?: QuestionDifficulty | null
  tags?: Array<string> | null
}

/**
 * Request body for deleting a question with optional rejection feedback.
 */
export type QuestionDeleteRequest = {
  /**
   * Reason for rejecting the question
   */
  rejection_reason?: RejectionReason | null
  /**
   * Optional additional feedback
   */
  rejection_feedback?: string | null
}

/**
 * Question difficulty levels.
 */
export type QuestionDifficulty = "easy" | "medium" | "hard"

/**
 * Maps a question to its best matching content.
 */
export type QuestionMapping = {
  /**
   * Question UUID
   */
  question_id: string
  /**
   * Truncated question text for display
   */
  question_text: string
  /**
   * Type of question (e.g., multiple_choice)
   */
  question_type: string
  /**
   * Indices of best matching sentences
   */
  best_matching_sentences: Array<number>
  /**
   * Highest similarity score to any sentence
   */
  best_similarity_score: number
}

/**
 * Public question schema for API responses.
 */
export type QuestionResponse = {
  id: string
  quiz_id: string
  question_type: QuestionType
  question_data: {
    [key: string]: unknown
  }
  difficulty?: QuestionDifficulty | null
  tags?: Array<string> | null
  is_approved: boolean
  approved_at?: string | null
  created_at?: string | null
  updated_at?: string | null
  canvas_item_id?: string | null
  module_id?: string | null
  rejection_reason?: string | null
  rejection_feedback?: string | null
}

/**
 * Enumeration of supported question types.
 *
 * To add a new question type:
 * 1. Add enum value here
 * 2. Create implementation in types/{type_name}.py
 * 3. Register in registry.py
 * 4. Add templates in templates/files/
 * See ADDING_NEW_TYPES.md for detailed instructions.
 */
export type QuestionType =
  | "multiple_choice"
  | "multiple_answer"
  | "fill_in_blank"
  | "matching"
  | "categorization"
  | "true_false"

/**
 * Schema for updating a question.
 */
export type QuestionUpdateRequest = {
  /**
   * Updated question data
   */
  question_data?: {
    [key: string]: unknown
  } | null
  difficulty?: QuestionDifficulty | null
  tags?: Array<string> | null
}

/**
 * Quiz model representing a quiz with questions generated from Canvas content.
 */
export type Quiz = {
  id?: string
  owner_id: string | null
  canvas_course_id: number
  canvas_course_name: string
  selected_modules?: {
    [key: string]: {
      [key: string]: unknown
    }
  }
  title: string
  /**
   * Total number of questions in the quiz
   */
  question_count?: number
  llm_model?: string
  llm_temperature?: number
  /**
   * Language for question generation
   */
  language?: QuizLanguage
  /**
   * Tone of voice for question generation
   */
  tone?: QuizTone
  /**
   * Custom instructions for the LLM during question generation
   */
  custom_instructions?: string | null
  /**
   * Consolidated quiz status
   */
  status?: QuizStatus
  /**
   * Specific failure reason when status is failed
   */
  failure_reason?: FailureReason | null
  last_status_update?: string
  extracted_content?: {
    [key: string]: unknown
  } | null
  /**
   * Timestamp when content extraction was completed
   */
  content_extracted_at?: string | null
  created_at?: string | null
  updated_at?: string | null
  /**
   * Canvas quiz assignment ID after export
   */
  canvas_quiz_id?: string | null
  /**
   * Timestamp when quiz was exported to Canvas
   */
  exported_at?: string | null
  /**
   * Additional metadata for tracking generation details
   */
  generation_metadata?: {
    [key: string]: unknown
  }
  /**
   * Soft delete flag for data preservation
   */
  deleted?: boolean
  /**
   * Timestamp when quiz was soft deleted
   */
  deleted_at?: string | null
}

/**
 * Response schema for quiz collaborators list.
 */
export type QuizCollaboratorsResponse = {
  quiz_id: string
  owner_id: string | null
  owner_name: string | null
  collaborators: Array<CollaboratorResponse>
  active_invites: Array<QuizInviteResponse>
}

/**
 * Schema for creating a new quiz with module-based questions.
 */
export type QuizCreate = {
  canvas_course_id: number
  canvas_course_name: string
  selected_modules: {
    [key: string]: ModuleSelection
  }
  title: string
  llm_model?: string
  llm_temperature?: number
  language?: QuizLanguage
  tone?: QuizTone
  /**
   * Custom instructions for the LLM during question generation
   */
  custom_instructions?: string | null
}

/**
 * Schema for creating a quiz invite.
 */
export type QuizInviteCreate = {
  /**
   * Days until expiration, null for no expiration
   */
  expires_in_days?: number | null
  /**
   * Max uses, null for unlimited
   */
  max_uses?: number | null
}

/**
 * Response schema for quiz invite.
 */
export type QuizInviteResponse = {
  id: string
  token: string
  invite_url: string
  quiz_id: string
  quiz_title: string
  created_at: string | null
  expires_at: string | null
  max_uses: number | null
  use_count: number
  is_revoked: boolean
}

/**
 * Supported languages for quiz question generation.
 */
export type QuizLanguage = "en" | "no"

/**
 * Consolidated status values for quiz workflow.
 */
export type QuizStatus =
  | "created"
  | "extracting_content"
  | "generating_questions"
  | "ready_for_review"
  | "ready_for_review_partial"
  | "exporting_to_canvas"
  | "published"
  | "failed"

/**
 * Tone of voice options for quiz question generation.
 */
export type QuizTone = "academic" | "casual" | "encouraging" | "professional"

/**
 * Schema for updating quiz settings.
 */
export type QuizUpdate = {
  title?: string | null
  llm_model?: string | null
  llm_temperature?: number | null
  language?: QuizLanguage | null
}

/**
 * Request schema for regenerating a single batch of questions.
 */
export type RegenerateBatchRequest = {
  /**
   * Module ID for the batch to regenerate
   */
  module_id: string
  /**
   * Question type to regenerate
   */
  question_type: QuestionType
  /**
   * Number of questions to generate (1-20)
   */
  count: number
  /**
   * Difficulty level for questions
   */
  difficulty: QuestionDifficulty
}

/**
 * Reasons for rejecting a generated question.
 */
export type RejectionReason =
  | "incorrect_answer"
  | "poor_wording"
  | "irrelevant_content"
  | "duplicate_question"
  | "too_easy"
  | "too_hard"
  | "quota_reached"
  | "topic_coverage"
  | "other"

/**
 * Coverage data for a single sentence.
 */
export type SentenceCoverage = {
  /**
   * Index of sentence within the page
   */
  sentence_index: number
  /**
   * The sentence text
   */
  text: string
  /**
   * Start character position in original content
   */
  start_char: number
  /**
   * End character position in original content
   */
  end_char: number
  /**
   * Similarity score (0=no match, 1=perfect match)
   */
  coverage_score: number
  /**
   * Coverage level: 'none', 'low', 'medium', 'high'
   */
  coverage_level: string
  /**
   * IDs of questions that match this sentence
   */
  matched_questions?: Array<string>
  /**
   * Highest similarity score among matched questions
   */
  top_question_similarity?: number | null
}

/**
 * Public user information schema.
 */
export type UserPublic = {
  id: string
  name: string
  onboarding_completed: boolean
}

/**
 * Schema for user self-update.
 */
export type UserUpdateMe = {
  name: string
  onboarding_completed?: boolean | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AuthLoginCanvasResponse = unknown

export type AuthAuthCanvasResponse = unknown

export type AuthLogoutCanvasResponse = {
  [key: string]: string
}

export type CanvasGetCoursesResponse = Array<CanvasCourse>

export type CanvasGetCourseModulesData = {
  courseId: number
}

export type CanvasGetCourseModulesResponse = Array<CanvasModule>

export type CanvasGetModuleItemsData = {
  courseId: number
  moduleId: number
}

export type CanvasGetModuleItemsResponse = Array<{
  [key: string]: unknown
}>

export type CanvasGetPageContentData = {
  courseId: number
  pageUrl: string
}

export type CanvasGetPageContentResponse = {
  [key: string]: unknown
}

export type CanvasGetFileInfoData = {
  courseId: number
  fileId: number
}

export type CanvasGetFileInfoResponse = {
  [key: string]: unknown
}

export type CoverageListCoverageModulesData = {
  quizId: string
}

export type CoverageListCoverageModulesResponse = ModuleListResponse

export type CoverageGetModuleCoverageData = {
  moduleId: string
  quizId: string
}

export type CoverageGetModuleCoverageResponse = ModuleCoverageResponse

export type QuestionsGetQuizQuestionsData = {
  /**
   * Only return approved questions
   */
  approvedOnly?: boolean
  /**
   * Maximum questions to return
   */
  limit?: number | null
  /**
   * Number of questions to skip
   */
  offset?: number
  /**
   * Filter by question type
   */
  questionType?: QuestionType | null
  quizId: string
}

export type QuestionsGetQuizQuestionsResponse = Array<QuestionResponse>

export type QuestionsCreateQuestionData = {
  quizId: string
  requestBody: QuestionCreateRequest
}

export type QuestionsCreateQuestionResponse = QuestionResponse

export type QuestionsGetQuestionData = {
  questionId: string
  quizId: string
}

export type QuestionsGetQuestionResponse = QuestionResponse

export type QuestionsUpdateQuestionData = {
  questionId: string
  quizId: string
  requestBody: QuestionUpdateRequest
}

export type QuestionsUpdateQuestionResponse = QuestionResponse

export type QuestionsDeleteQuestionData = {
  questionId: string
  quizId: string
  requestBody?: QuestionDeleteRequest | null
}

export type QuestionsDeleteQuestionResponse = {
  [key: string]: string
}

export type QuestionsBulkApproveQuestionsData = {
  quizId: string
  requestBody: BulkApproveRequest
}

export type QuestionsBulkApproveQuestionsResponse = BulkOperationResponse

export type QuestionsBulkDeleteQuestionsData = {
  quizId: string
  requestBody: BulkDeleteRequest
}

export type QuestionsBulkDeleteQuestionsResponse = BulkOperationResponse

export type QuestionsApproveQuestionData = {
  questionId: string
  quizId: string
}

export type QuestionsApproveQuestionResponse = QuestionResponse

export type QuizGetUserQuizzesEndpointResponse = Array<Quiz>

export type QuizCreateNewQuizData = {
  requestBody: QuizCreate
}

export type QuizCreateNewQuizResponse = Quiz

export type QuizUploadManualModuleData = {
  formData: Body_quiz_upload_manual_module
}

export type QuizUploadManualModuleResponse = ManualModuleResponse

export type QuizGetQuizData = {
  quizId: string
}

export type QuizGetQuizResponse = Quiz

export type QuizUpdateQuizEndpointData = {
  quizId: string
  requestBody: QuizUpdate
}

export type QuizUpdateQuizEndpointResponse = Quiz

export type QuizDeleteQuizEndpointData = {
  quizId: string
}

export type QuizDeleteQuizEndpointResponse = unknown

export type QuizTriggerContentExtractionData = {
  quizId: string
}

export type QuizTriggerContentExtractionResponse = {
  [key: string]: string
}

export type QuizTriggerQuestionGenerationData = {
  quizId: string
}

export type QuizTriggerQuestionGenerationResponse = {
  [key: string]: string
}

export type QuizRegenerateSingleBatchData = {
  quizId: string
  requestBody: RegenerateBatchRequest
}

export type QuizRegenerateSingleBatchResponse = {
  [key: string]: string
}

export type QuizGetQuizQuestionStatsData = {
  quizId: string
}

export type QuizGetQuizQuestionStatsResponse = {
  [key: string]: number
}

export type QuizExportQuizToCanvasData = {
  quizId: string
}

export type QuizExportQuizToCanvasResponse = {
  [key: string]: string
}

export type QuizSharingCreateInviteData = {
  quizId: string
  requestBody: QuizInviteCreate
}

export type QuizSharingCreateInviteResponse = QuizInviteResponse

export type QuizSharingListCollaboratorsData = {
  quizId: string
}

export type QuizSharingListCollaboratorsResponse = QuizCollaboratorsResponse

export type QuizSharingRemoveCollaboratorEndpointData = {
  collaboratorId: string
  quizId: string
}

export type QuizSharingRemoveCollaboratorEndpointResponse = {
  [key: string]: string
}

export type QuizSharingRevokeInviteEndpointData = {
  inviteId: string
  quizId: string
}

export type QuizSharingRevokeInviteEndpointResponse = {
  [key: string]: string
}

export type QuizSharingGetInviteInfoData = {
  token: string
}

export type QuizSharingGetInviteInfoResponse = InviteInfoResponse

export type QuizSharingAcceptInviteData = {
  token: string
}

export type QuizSharingAcceptInviteResponse = AcceptInviteResponse

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = unknown

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UtilsHealthCheckResponse = boolean
