{
 "title": "QuizCrafter Application Monitoring",
 "tags": [
  "quizcrafter",
  "application"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate({service=\"backend\"} [$__interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "count(rate({service=\"backend\"} [$__interval]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate({service=\"backend\"} |~ \"error|failed|502|500|400|404\" [$__interval]))",
     "legendFormat": "Error Rate (%)"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({service=\"backend\"} [$__interval]))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Recent Application Events",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service=\"backend\"} |~ \"warning|error\""
    }
   ]
  }
 ]
}