"""add_custom_instructions_to_quiz

Revision ID: 08982fd53ba0
Revises: d867ad0af218
Create Date: 2026-01-22 08:56:39.719729

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08982fd53ba0'
down_revision = 'd867ad0af218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('custom_instructions', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'custom_instructions')
    # ### end Alembic commands ###
