"""add_rejection_feedback_fields

Revision ID: 1b928666719e
Revises: 08982fd53ba0
Create Date: 2026-01-22 11:40:45.027682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1b928666719e'
down_revision = '08982fd53ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('question', sa.Column('rejection_feedback', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'rejection_feedback')
    op.drop_column('question', 'rejection_reason')
    # ### end Alembic commands ###
