"""add_module_id_to_questions

Revision ID: d751aaf1a0b4
Revises: d4898d030e58
Create Date: 2025-08-27 10:19:10.370504

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd751aaf1a0b4'
down_revision = 'd4898d030e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'module_id')
    # ### end Alembic commands ###
