"""add_quiz_sharing_tables

Revision ID: d867ad0af218
Revises: d751aaf1a0b4
Create Date: 2026-01-21 12:31:26.774465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd867ad0af218'
down_revision = 'd751aaf1a0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizcollaborator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_id', name='uq_quiz_collaborator')
    )
    op.create_index(op.f('ix_quizcollaborator_quiz_id'), 'quizcollaborator', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizcollaborator_user_id'), 'quizcollaborator', ['user_id'], unique=False)
    op.create_table('quizinvite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_quiz_invite_token')
    )
    op.create_index(op.f('ix_quizinvite_is_revoked'), 'quizinvite', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_quizinvite_quiz_id'), 'quizinvite', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizinvite_token'), 'quizinvite', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizinvite_token'), table_name='quizinvite')
    op.drop_index(op.f('ix_quizinvite_quiz_id'), table_name='quizinvite')
    op.drop_index(op.f('ix_quizinvite_is_revoked'), table_name='quizinvite')
    op.drop_table('quizinvite')
    op.drop_index(op.f('ix_quizcollaborator_user_id'), table_name='quizcollaborator')
    op.drop_index(op.f('ix_quizcollaborator_quiz_id'), table_name='quizcollaborator')
    op.drop_table('quizcollaborator')
    # ### end Alembic commands ###
