/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LoginSuccessRouteImport } from './routes/login/success'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutQuizzesRouteImport } from './routes/_layout/quizzes'
import { Route as LayoutQuestionTypesNoRouteImport } from './routes/_layout/question-types-no'
import { Route as LayoutQuestionTypesRouteImport } from './routes/_layout/question-types'
import { Route as LayoutPrivacyPolicyNoRouteImport } from './routes/_layout/privacy-policy-no'
import { Route as LayoutPrivacyPolicyRouteImport } from './routes/_layout/privacy-policy'
import { Route as LayoutCreateQuizRouteImport } from './routes/_layout/create-quiz'
import { Route as LayoutQuizIdRouteImport } from './routes/_layout/quiz.$id'
import { Route as LayoutInviteTokenRouteImport } from './routes/_layout/invite.$token'
import { Route as LayoutQuizIdIndexRouteImport } from './routes/_layout/quiz.$id.index'
import { Route as LayoutQuizIdQuestionsRouteImport } from './routes/_layout/quiz.$id.questions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LoginSuccessRoute = LoginSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => LoginRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizzesRoute = LayoutQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionTypesNoRoute = LayoutQuestionTypesNoRouteImport.update({
  id: '/question-types-no',
  path: '/question-types-no',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionTypesRoute = LayoutQuestionTypesRouteImport.update({
  id: '/question-types',
  path: '/question-types',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyPolicyNoRoute = LayoutPrivacyPolicyNoRouteImport.update({
  id: '/privacy-policy-no',
  path: '/privacy-policy-no',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyPolicyRoute = LayoutPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateQuizRoute = LayoutCreateQuizRouteImport.update({
  id: '/create-quiz',
  path: '/create-quiz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizIdRoute = LayoutQuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInviteTokenRoute = LayoutInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizIdIndexRoute = LayoutQuizIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutQuizIdRoute,
} as any)
const LayoutQuizIdQuestionsRoute = LayoutQuizIdQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => LayoutQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/create-quiz': typeof LayoutCreateQuizRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/privacy-policy-no': typeof LayoutPrivacyPolicyNoRoute
  '/question-types': typeof LayoutQuestionTypesRoute
  '/question-types-no': typeof LayoutQuestionTypesNoRoute
  '/quizzes': typeof LayoutQuizzesRoute
  '/settings': typeof LayoutSettingsRoute
  '/login/success': typeof LoginSuccessRoute
  '/invite/$token': typeof LayoutInviteTokenRoute
  '/quiz/$id': typeof LayoutQuizIdRouteWithChildren
  '/quiz/$id/questions': typeof LayoutQuizIdQuestionsRoute
  '/quiz/$id/': typeof LayoutQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteWithChildren
  '/create-quiz': typeof LayoutCreateQuizRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/privacy-policy-no': typeof LayoutPrivacyPolicyNoRoute
  '/question-types': typeof LayoutQuestionTypesRoute
  '/question-types-no': typeof LayoutQuestionTypesNoRoute
  '/quizzes': typeof LayoutQuizzesRoute
  '/settings': typeof LayoutSettingsRoute
  '/login/success': typeof LoginSuccessRoute
  '/': typeof LayoutIndexRoute
  '/invite/$token': typeof LayoutInviteTokenRoute
  '/quiz/$id/questions': typeof LayoutQuizIdQuestionsRoute
  '/quiz/$id': typeof LayoutQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_layout/create-quiz': typeof LayoutCreateQuizRoute
  '/_layout/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/_layout/privacy-policy-no': typeof LayoutPrivacyPolicyNoRoute
  '/_layout/question-types': typeof LayoutQuestionTypesRoute
  '/_layout/question-types-no': typeof LayoutQuestionTypesNoRoute
  '/_layout/quizzes': typeof LayoutQuizzesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/login/success': typeof LoginSuccessRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/invite/$token': typeof LayoutInviteTokenRoute
  '/_layout/quiz/$id': typeof LayoutQuizIdRouteWithChildren
  '/_layout/quiz/$id/questions': typeof LayoutQuizIdQuestionsRoute
  '/_layout/quiz/$id/': typeof LayoutQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/create-quiz'
    | '/privacy-policy'
    | '/privacy-policy-no'
    | '/question-types'
    | '/question-types-no'
    | '/quizzes'
    | '/settings'
    | '/login/success'
    | '/invite/$token'
    | '/quiz/$id'
    | '/quiz/$id/questions'
    | '/quiz/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/create-quiz'
    | '/privacy-policy'
    | '/privacy-policy-no'
    | '/question-types'
    | '/question-types-no'
    | '/quizzes'
    | '/settings'
    | '/login/success'
    | '/'
    | '/invite/$token'
    | '/quiz/$id/questions'
    | '/quiz/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/create-quiz'
    | '/_layout/privacy-policy'
    | '/_layout/privacy-policy-no'
    | '/_layout/question-types'
    | '/_layout/question-types-no'
    | '/_layout/quizzes'
    | '/_layout/settings'
    | '/login/success'
    | '/_layout/'
    | '/_layout/invite/$token'
    | '/_layout/quiz/$id'
    | '/_layout/quiz/$id/questions'
    | '/_layout/quiz/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/login/success': {
      id: '/login/success'
      path: '/success'
      fullPath: '/login/success'
      preLoaderRoute: typeof LoginSuccessRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quizzes': {
      id: '/_layout/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof LayoutQuizzesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/question-types-no': {
      id: '/_layout/question-types-no'
      path: '/question-types-no'
      fullPath: '/question-types-no'
      preLoaderRoute: typeof LayoutQuestionTypesNoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/question-types': {
      id: '/_layout/question-types'
      path: '/question-types'
      fullPath: '/question-types'
      preLoaderRoute: typeof LayoutQuestionTypesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy-policy-no': {
      id: '/_layout/privacy-policy-no'
      path: '/privacy-policy-no'
      fullPath: '/privacy-policy-no'
      preLoaderRoute: typeof LayoutPrivacyPolicyNoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy-policy': {
      id: '/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPrivacyPolicyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create-quiz': {
      id: '/_layout/create-quiz'
      path: '/create-quiz'
      fullPath: '/create-quiz'
      preLoaderRoute: typeof LayoutCreateQuizRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quiz/$id': {
      id: '/_layout/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof LayoutQuizIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invite/$token': {
      id: '/_layout/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof LayoutInviteTokenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quiz/$id/': {
      id: '/_layout/quiz/$id/'
      path: '/'
      fullPath: '/quiz/$id/'
      preLoaderRoute: typeof LayoutQuizIdIndexRouteImport
      parentRoute: typeof LayoutQuizIdRoute
    }
    '/_layout/quiz/$id/questions': {
      id: '/_layout/quiz/$id/questions'
      path: '/questions'
      fullPath: '/quiz/$id/questions'
      preLoaderRoute: typeof LayoutQuizIdQuestionsRouteImport
      parentRoute: typeof LayoutQuizIdRoute
    }
  }
}

interface LayoutQuizIdRouteChildren {
  LayoutQuizIdQuestionsRoute: typeof LayoutQuizIdQuestionsRoute
  LayoutQuizIdIndexRoute: typeof LayoutQuizIdIndexRoute
}

const LayoutQuizIdRouteChildren: LayoutQuizIdRouteChildren = {
  LayoutQuizIdQuestionsRoute: LayoutQuizIdQuestionsRoute,
  LayoutQuizIdIndexRoute: LayoutQuizIdIndexRoute,
}

const LayoutQuizIdRouteWithChildren = LayoutQuizIdRoute._addFileChildren(
  LayoutQuizIdRouteChildren,
)

interface LayoutRouteChildren {
  LayoutCreateQuizRoute: typeof LayoutCreateQuizRoute
  LayoutPrivacyPolicyRoute: typeof LayoutPrivacyPolicyRoute
  LayoutPrivacyPolicyNoRoute: typeof LayoutPrivacyPolicyNoRoute
  LayoutQuestionTypesRoute: typeof LayoutQuestionTypesRoute
  LayoutQuestionTypesNoRoute: typeof LayoutQuestionTypesNoRoute
  LayoutQuizzesRoute: typeof LayoutQuizzesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutInviteTokenRoute: typeof LayoutInviteTokenRoute
  LayoutQuizIdRoute: typeof LayoutQuizIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCreateQuizRoute: LayoutCreateQuizRoute,
  LayoutPrivacyPolicyRoute: LayoutPrivacyPolicyRoute,
  LayoutPrivacyPolicyNoRoute: LayoutPrivacyPolicyNoRoute,
  LayoutQuestionTypesRoute: LayoutQuestionTypesRoute,
  LayoutQuestionTypesNoRoute: LayoutQuestionTypesNoRoute,
  LayoutQuizzesRoute: LayoutQuizzesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutInviteTokenRoute: LayoutInviteTokenRoute,
  LayoutQuizIdRoute: LayoutQuizIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface LoginRouteChildren {
  LoginSuccessRoute: typeof LoginSuccessRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSuccessRoute: LoginSuccessRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
