# Staging Deployment Workflow
# Copy this file to .github/workflows/deploy-staging.yml

name: Deploy to Staging

on:
  push:
    branches: [develop, "release/*"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  BACKEND_IMAGE: ${{ secrets.ACR_LOGIN_SERVER }}/quizcrafter-backend
  RESOURCE_GROUP: quizcrafter-staging-rg
  CONTAINER_APP_NAME: quizcrafter-staging-backend

jobs:
  # ============================================
  # Job 1: Run tests and linting
  # ============================================
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install backend dependencies
        run: uv sync
        working-directory: backend

      - name: Run linting
        run: uv run bash scripts/lint.sh
        working-directory: backend

      - name: Run backend tests
        run: uv run bash scripts/test.sh
        working-directory: backend
        env:
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          SECRET_KEY: test-secret-key-for-ci
          FIRST_SUPERUSER: admin@test.com
          FIRST_SUPERUSER_PASSWORD: testpassword123
          CANVAS_CLIENT_ID: test-client-id
          CANVAS_CLIENT_SECRET: test-client-secret
          CANVAS_REDIRECT_URI: http://localhost/callback
          CANVAS_BASE_URL: https://canvas.test.com

  # ============================================
  # Job 2: Build and deploy to staging
  # ============================================
  build-and-deploy:
    name: Build & Deploy to Staging
    needs: test
    runs-on: ubuntu-latest
    environment: staging
    # Only deploy on push, not on PR (to save costs)
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:staging-${{ github.sha }}
            ${{ env.BACKEND_IMAGE }}:staging-latest
          cache-from: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max

      - name: Deploy backend to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.BACKEND_IMAGE }}:staging-${{ github.sha }}

      # Frontend deployment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend
        env:
          # UPDATE THIS with your actual staging API URL
          VITE_API_URL: https://api-staging.quizcrafter.yourdomain.com

      - name: Deploy frontend to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend
          output_location: dist
          skip_app_build: true

      - name: Post deployment summary
        run: |
          echo "## Staging Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### URLs" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend: https://staging.quizcrafter.yourdomain.com" >> $GITHUB_STEP_SUMMARY
          echo "- Backend: https://api-staging.quizcrafter.yourdomain.com" >> $GITHUB_STEP_SUMMARY

  # ============================================
  # Job 3: PR Preview deployment (optional)
  # ============================================
  pr-preview:
    name: PR Preview
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install and build frontend
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          # For PR previews, point to staging API
          VITE_API_URL: https://api-staging.quizcrafter.yourdomain.com

      # Static Web Apps automatically creates preview environments for PRs
      - name: Deploy PR preview
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend
          output_location: dist
          skip_app_build: true
