# Production Deployment Workflow
# Copy this file to .github/workflows/deploy-prod.yml

name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  BACKEND_IMAGE: ${{ secrets.ACR_LOGIN_SERVER }}/quizcrafter-backend
  RESOURCE_GROUP: quizcrafter-prod-rg
  CONTAINER_APP_NAME: quizcrafter-prod-backend

jobs:
  # ============================================
  # Job 1: Run tests and linting
  # ============================================
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install backend dependencies
        run: uv sync
        working-directory: backend

      - name: Run linting (mypy + ruff)
        run: uv run bash scripts/lint.sh
        working-directory: backend

      - name: Run backend tests
        run: uv run bash scripts/test.sh
        working-directory: backend
        env:
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          SECRET_KEY: test-secret-key-for-ci
          FIRST_SUPERUSER: admin@test.com
          FIRST_SUPERUSER_PASSWORD: testpassword123
          CANVAS_CLIENT_ID: test-client-id
          CANVAS_CLIENT_SECRET: test-client-secret
          CANVAS_REDIRECT_URI: http://localhost/callback
          CANVAS_BASE_URL: https://canvas.test.com

  # ============================================
  # Job 2: Build and push backend Docker image
  # ============================================
  build-backend:
    name: Build Backend Image
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
            ${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max

  # ============================================
  # Job 3: Deploy backend to Azure Container Apps
  # ============================================
  deploy-backend:
    name: Deploy Backend
    needs: build-backend
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Verify deployment
        run: |
          # Wait for the new revision to be ready
          sleep 30

          # Get the app URL
          APP_URL=$(az containerapp show \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query properties.configuration.ingress.fqdn -o tsv)

          # Health check
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://${APP_URL}/api/v1/utils/health-check/")

          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Health check failed with status $HTTP_STATUS"
            exit 1
          fi

          echo "Backend deployment verified successfully"

  # ============================================
  # Job 4: Build and deploy frontend
  # ============================================
  deploy-frontend:
    name: Deploy Frontend
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend
        env:
          # UPDATE THIS with your actual production API URL
          VITE_API_URL: https://api.quizcrafter.yourdomain.com

      - name: Deploy to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend
          output_location: dist
          skip_app_build: true

  # ============================================
  # Job 5: Post-deployment notification (optional)
  # ============================================
  notify:
    name: Notify
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Backend Status:** ${{ needs.deploy-backend.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend Status:** ${{ needs.deploy-frontend.result }}" >> $GITHUB_STEP_SUMMARY
