# Infrastructure Deployment Workflow
# Copy this file to .github/workflows/infrastructure.yml
#
# This workflow deploys Azure infrastructure using Bicep templates.
# It should be run manually or when infrastructure changes are made.

name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      deploy_database:
        description: 'Deploy database changes'
        required: false
        default: false
        type: boolean

env:
  AZURE_RESOURCE_GROUP_DEV: quizcrafter-dev-rg
  AZURE_RESOURCE_GROUP_STAGING: quizcrafter-staging-rg
  AZURE_RESOURCE_GROUP_PROD: quizcrafter-prod-rg

jobs:
  # ============================================
  # Job 1: Validate Bicep templates
  # ============================================
  validate:
    name: Validate Templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep syntax
        run: |
          az bicep build --file infrastructure/environments/${{ inputs.environment }}/main.bicep

      - name: What-if deployment
        run: |
          RESOURCE_GROUP="quizcrafter-${{ inputs.environment }}-rg"

          az deployment group what-if \
            --name "quizcrafter-${{ inputs.environment }}-infra-${{ github.run_number }}" \
            --resource-group $RESOURCE_GROUP \
            --template-file infrastructure/environments/${{ inputs.environment }}/main.bicep \
            --parameters @infrastructure/environments/${{ inputs.environment }}/parameters.json

  # ============================================
  # Job 2: Deploy infrastructure
  # ============================================
  deploy:
    name: Deploy to ${{ inputs.environment }}
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set resource group
        id: set-rg
        run: |
          case "${{ inputs.environment }}" in
            dev)
              echo "resource_group=${{ env.AZURE_RESOURCE_GROUP_DEV }}" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "resource_group=${{ env.AZURE_RESOURCE_GROUP_STAGING }}" >> $GITHUB_OUTPUT
              ;;
            prod)
              echo "resource_group=${{ env.AZURE_RESOURCE_GROUP_PROD }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ steps.set-rg.outputs.resource_group }}
          template: infrastructure/environments/${{ inputs.environment }}/main.bicep
          parameters: infrastructure/environments/${{ inputs.environment }}/parameters.json
          deploymentName: quizcrafter-${{ inputs.environment }}-${{ github.run_number }}

      - name: Output deployment results
        run: |
          az deployment group show \
            --name "quizcrafter-${{ inputs.environment }}-${{ github.run_number }}" \
            --resource-group ${{ steps.set-rg.outputs.resource_group }} \
            --query properties.outputs

  # ============================================
  # Job 3: Run database migrations (optional)
  # ============================================
  migrate-database:
    name: Run Database Migrations
    needs: deploy
    runs-on: ubuntu-latest
    if: inputs.deploy_database == true
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync
        working-directory: backend

      - name: Get database connection info
        id: db-info
        run: |
          DB_HOST=$(az postgres flexible-server show \
            --name "quizcrafter-${{ inputs.environment }}-db" \
            --resource-group "quizcrafter-${{ inputs.environment }}-rg" \
            --query fullyQualifiedDomainName -o tsv)
          echo "db_host=$DB_HOST" >> $GITHUB_OUTPUT

      - name: Run Alembic migrations
        run: |
          cd backend
          uv run alembic upgrade head
        env:
          POSTGRES_SERVER: ${{ steps.db-info.outputs.db_host }}
          POSTGRES_PORT: 5432
          POSTGRES_USER: quizcrafteradmin
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: quizcrafter

      - name: Verify migration
        run: |
          cd backend
          uv run alembic current
        env:
          POSTGRES_SERVER: ${{ steps.db-info.outputs.db_host }}
          POSTGRES_PORT: 5432
          POSTGRES_USER: quizcrafteradmin
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: quizcrafter
