server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      # Parse Docker JSON log format
      - json:
          expressions:
            log: log
            stream: stream
            time: time
            attrs: attrs

      # Extract service name from attrs (this is our container identifier)
      - json:
          expressions:
            service: service
            version: version
          source: attrs

      # Set timestamp
      - timestamp:
          format: RFC3339Nano
          source: time

      # Add base labels
      - labels:
          stream:
          service:
          version:

      # For backend logs, parse structured logging data
      - match:
          selector: '{service="backend"}'
          stages:
            # Extract log level
            - regex:
                expression: '\[\033\[32m\033\[1m(?P<level>\w+)\s+\033\[0m\]'
                source: log

            # Extract status code
            - regex:
                expression: 'status_code\033\[0m=\033\[35m(?P<status_code>\d+)\033\[0m'
                source: log

            # Extract duration in milliseconds
            - regex:
                expression: 'duration_ms\033\[0m=\033\[35m(?P<duration_ms>[\d.]+)\033\[0m'
                source: log

            # Add extracted fields as labels
            - labels:
                level:
                status_code:
                duration_ms:

      # Set the final log output
      - output:
          source: log
