name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - "my_backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "my_backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my_backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run linter
        run: poetry run ruff check .
      - name: Run tests
        run: poetry run pytest
